// angular2/src/app/articles/components/header/header.component.ts
import 'rxjs/add/operator/switchMap';

import { Component } from '@angular/core';

@Component({
  selector: 'header',
  templateUrl: 'header.component.html',
})
export class HeaderComponent { }


<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </button>
      <a class="navbar-brand" routerLink="/">Blog</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a routerLink="/articles" routerLinkActive="active">Articles</a></li>
      </ul>
    </div>
  </div>
</nav>

// react-redux/src/components/common/Header.js
import React, {PropTypes} from 'react';
import { Link, IndexLink } from 'react-router';

const Header = () => {
  return (
    <nav className="navbar navbar-inverse navbar-fixed-top">
      <div className="container">
        <div className="navbar-header">
          <button type="button" className="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
            <span className="icon-bar"></span>
            <span className="icon-bar"></span>
            <span className="icon-bar"></span>
          </button>
          <Link className="navbar-brand" to="/">Blog</Link>
        </div>
        <div id="navbar" className="navbar-collapse collapse">
          <ul className="nav navbar-nav">
            <li><Link to="/articles" activeclassNameName="active">Articles</Link></li>
          </ul>
        </div>
      </div>
    </nav>
  );
};

Header.propTypes = {};

export default Header;
