// angular2/src/app/articles/components/articles/articles.component.ts
import { Component, OnInit } from '@angular/core';

import { Article } from '../../classes/article';
import { ArticlesService } from '../../services/articles.service';

@Component({
  selector: 'articles',
  templateUrl: './articles.component.html',
})
export class ArticlesComponent implements OnInit {
  articles: Article[];

  constructor(
    private articlesService: ArticlesService) {
    console.log('--- articles.component.ts: private articlesService: ArticlesService"');
  }

  ngOnInit(): void {
    this.getArticles();
  }

  getArticles(): void {
    this.articlesService
      .getArticles()
      .then(articles => this.articles = articles);
  }

  deleteArticle(article: Article): void {
    console.log('--- articles.component.ts: deleteArticle()');

    this.articlesService
      .deleteArticle(article.id)
      .then(() => console.log('Success: article deleted'))
      .catch(error => {
        console.error(error);
      });
  }
}

console.log('--- articles.component.html: (click)="deleteArticle(article);"');


<h1>Articles</h1>

<a href="" [routerLink]="['/article']" class="btn btn-primary">Create</a>
<br><br>

<table class="table">
  <thead>
    <tr>
      <th>Article</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr *ngFor="let article of articles">
      <td>
        <a href="" [routerLink]="['/article', article.id]">
          {{article.id}}
          {{article.title}}
        </a>
      </td>
      <td>
        <a href="" (click)="deleteArticle(article); $event.preventDefault();">Delete</a>
      </td>
    </tr>
  </tbody>
</table>

// vue-vuex/src/modules/articles/Articles.vue
<template>
  <div>
    <h1>Articles</h1>

    <router-link to="/article" class="btn btn-primary">Create</router-link>
    <br><br>

    <table class="table">
      <thead>
        <tr>
          <th>Article</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="article in articles">
          <td>
            <router-link :to="{ path: '/article/'+article.id}">
              {{article.id}}
              {{article.title}}
            </router-link>
          </td>
          <td>
            <a href="" v-on:click="console.log('--- Articles.vue: v-on:click'); deleteArticle(article); $event.preventDefault();">Delete</a>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script>
export default {
  name: 'articles',
  computed: {
    articles () {
      return this.$store.state.articles.articles
    },
    console () {
      return console
    }
  },

  methods: {
    deleteArticle (article) {
      console.log('--- Articles.vue: deleteArticle()')

      this.$store.dispatch('deleteArticle', { id: article.id })
        .then(() => console.log('Success: article deleted'))
        .catch(error => {
          console.error(error)
        })
    }
  },

  created () {
    console.log('--- Articles.vue: v-on:click="deleteArticle(article);"')
    this.$store.dispatch('getArticles')
  }
}

</script>

<style scoped>
</style>
