// vue-vuex/src/modules/articles/Article.vue
<template>
  <div v-if="article" v-on:submit="saveArticle($event)">
    <h1>{{ (article.id) ? 'Update' : 'Create'}}</h1>
    <form>
      <div class="form-group" v-if="article.id">
        <label>id</label>
        {{article.id}}
      </div>
      
      <div class="form-group">
        <label for="title">title</label>
        <input v-model="article.title" type="input" class="form-control" id="title" name="title" placeholder="title" autocomplete="off" autofocus>
      </div>

      <div class="form-group">
        <label for="text">text</label>
        <textarea v-model="article.text" class="form-control" id="text" name="text" placeholder="text" autocomplete="off"></textarea>
      </div>

      <button class="btn btn-default" type="button" v-on:click="goToArticles()">Cancel</button>
      <button class="btn btn-primary" type="submit">Save</button>
    </form>
  </div>
</template>

<script>
export default {
  name: 'article',
  computed: {
    article () {
      return this.$store.state.articles.article
    }
  },

  methods: {
    goToArticles () {
      this.$router.push('/articles/')
    },

    saveArticle (event) {
      event.preventDefault()
      this.$store.dispatch('saveArticle', { article: this.article })
        .then(() => {
          console.log('Success: article saved')
          this.goToArticles()
        })
        .catch(error => {
          console.error(error)
        })
    }
  },

  created () {
    let id = this.$route.params.id
    if (id) {
      this.$store.dispatch('getArticleById', { id: id })
    } else {
      this.$store.dispatch('getNewArticle')
    }
  }
}
</script>

<style scoped>
</style>

// angular2/src/app/articles/components/article/article.component.ts
import 'rxjs/add/operator/switchMap';

import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Params } from '@angular/router';
import { Router } from '@angular/router';

import { Article } from '../../classes/article';
import { ArticlesService } from '../../services/articles.service';

@Component({
  selector: 'article',
  templateUrl: './article.component.html',
})
export class ArticleComponent implements OnInit {
  article: Article;

  constructor(
    private articlesService: ArticlesService,
    private route: ActivatedRoute,
    private router: Router
  ) { }

  ngOnInit(): void {
    this.route.params.subscribe(params => {
      if (params['id']) {
        this.getArticleById();
      } else {
        this.article = new Article();
      }
    });
  }

  getArticleById() {
    this.route.params
      .switchMap((params: Params) => this.articlesService.getArticleById(+params['id']))
      .subscribe(article => this.article = article);
  }

  goToArticles(): void {
    this.router.navigate(['/articles']);
  }

  save(): void {
    this.articlesService.save(this.article)
      .then(() => {
        console.log('Success: article saved');
        this.goToArticles();
      })
      .catch(error => {
        console.error(error);
      });
  }
}

<div *ngIf="article">
  <h1>{{ (article.id) ? 'Update' : 'Create'}}</h1>
  <form (submit)="saveArticle()">
    <div class="form-group" *ngIf="article.id">
      <label>id</label>
      {{article.id}}
    </div>
    
    <div class="form-group">
      <label for="title">title</label>
      <input [(ngModel)]="article.title" type="input" class="form-control" id="title" name="title" placeholder="title" autocomplete="off" autofocus>
    </div>

    <div class="form-group">
      <label for="text">text</label>
      <textarea [(ngModel)]="article.text" class="form-control" id="text" name="text" placeholder="text" autocomplete="off"></textarea>
    </div>

    <button class="btn btn-default" type="button" (click)="goToArticles()" >Cancel</button>
    <button class="btn btn-primary" type="submit">Save</button>
  </form>
</div>
